import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getAuthContext } from "@/server/auth/context";
import { getMatterBundle, isValidUuid } from "@/server/matters/queries";
import { listAdversarialCritiquesForMatter } from "@/server/adversarial/queries";
import { getAdversarialWorkspaceSummary } from "@/server/adversarial/summary";
import { AdversarialBanners } from "@/features/adversarial/adversarial-banners";
import { CreateAdversarialCritiqueForm } from "@/features/adversarial/create-adversarial-critique-form";
import { StrategyIssuePanels } from "@/features/strategy/strategy-issue-panels";
import { ArgumentInputSummaryPanel } from "@/features/argument/argument-input-summary";

export const metadata = { title: "Adversarial — LEXOS" };

type PageProps = { params: Promise<{ matterId: string }> };

export default async function MatterAdversarialPage({ params }: PageProps) {
  const { matterId } = await params;
  const ctx = await getAuthContext();
  if (!ctx) redirect("/login");
  if (!isValidUuid(matterId)) notFound();

  const supabase = await createSupabaseServerClient();
  const bundle = await getMatterBundle(supabase, matterId, ctx);
  if (!bundle) notFound();

  const [critiques, summary] = await Promise.all([
    listAdversarialCritiquesForMatter(supabase, matterId),
    getAdversarialWorkspaceSummary(supabase, matterId),
  ]);

  if (!summary) notFound();

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Adversarial review (W9)</h2>
        <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
          Operator-driven stress-test of argument drafts. Internal work product only — not filing-ready, not
          client-facing by default, and not generated by an autonomous adversary model.
        </p>
        <p className="mt-2 text-xs text-zinc-500">
          <Link
            href={`/matters/${matterId}/argument`}
            className="font-medium text-indigo-600 hover:underline dark:text-indigo-400"
          >
            Argument (W8)
          </Link>
        </p>
      </div>

      <AdversarialBanners />

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <section>
            <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Adversarial critiques</h3>
            {critiques.length === 0 ? (
              <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">No critiques yet.</p>
            ) : (
              <ul
                data-testid="adversarial-critique-list"
                className="mt-2 divide-y divide-zinc-200 rounded-lg border border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800"
              >
                {critiques.map((c) => (
                  <li key={c.id} className="flex flex-wrap items-center justify-between gap-2 px-3 py-2 text-sm">
                    <Link
                      href={`/matters/${matterId}/adversarial/${c.id}`}
                      className="font-medium text-indigo-600 hover:underline dark:text-indigo-400"
                    >
                      {(c.title ?? "Untitled").slice(0, 120)}
                    </Link>
                    <span className="text-xs text-zinc-500">
                      {c.status} · v{c.version ?? 1} · {new Date(c.updated_at).toLocaleString()}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </section>

          <CreateAdversarialCritiqueForm matterId={matterId} summary={summary} />

          <StrategyIssuePanels matterId={matterId} summary={summary} />
        </div>

        <aside className="rounded-lg border border-zinc-200 bg-zinc-50 p-4 dark:border-zinc-800 dark:bg-zinc-900/40">
          <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Input summary</h3>
          <div className="mt-3">
            <ArgumentInputSummaryPanel
              matterId={matterId}
              summary={summary}
              workflowAdvanceHint="adversarial"
              argumentDraftOptions={summary.argumentDraftOptions}
            />
          </div>
        </aside>
      </div>
    </div>
  );
}
